export const translations = {
  id: {
    title: 'AI Business Model Canvas Generator',
    subtitle: 'Ubah ide bisnis Anda menjadi Business Model Canvas yang komprehensif dengan AI',
    describeIdea: 'Deskripsikan Ide Bisnis Anda',
    placeholder: 'Contoh: Platform marketplace yang menghubungkan petani lokal dengan konsumen di kota besar. Fokus pada produk organik segar dengan sistem pre-order dan pengiriman same-day...',
    errorEmpty: 'Mohon masukkan deskripsi ide bisnis Anda.',
    generate: 'Generate Business Model Canvas',
    generating: 'Menghasilkan Business Model Canvas...',
    download: 'Download',
    downloadTxt: 'Download TXT',
    downloadPdf: 'Download PDF',
    downloadCsv: 'Download CSV',
    newIdea: 'Buat Baru',
    businessIdea: 'Ide Bisnis Anda:',
    businessModelCanvas: 'BUSINESS MODEL CANVAS',
    
    // BMC Blocks
    keyPartners: 'Key Partners',
    keyActivities: 'Key Activities',
    keyResources: 'Key Resources',
    valuePropositions: 'Value Propositions',
    customerRelationships: 'Customer Relationships',
    channels: 'Channels',
    customerSegments: 'Customer Segments',
    costStructure: 'Cost Structure',
    revenueStreams: 'Revenue Streams',
    
    // Tooltips
    tooltips: {
      keyPartners: 'Mitra kunci yang membantu bisnis Anda beroperasi dan mencapai tujuan',
      keyActivities: 'Aktivitas utama yang diperlukan untuk menjalankan model bisnis',
      keyResources: 'Aset dan sumber daya yang diperlukan untuk menciptakan nilai',
      valuePropositions: 'Nilai unik yang ditawarkan kepada pelanggan',
      customerRelationships: 'Cara Anda berinteraksi dan membangun hubungan dengan pelanggan',
      channels: 'Saluran distribusi untuk menjangkau dan melayani pelanggan',
      customerSegments: 'Kelompok pelanggan target yang ingin Anda layani',
      costStructure: 'Biaya utama yang terlibat dalam menjalankan bisnis',
      revenueStreams: 'Cara bisnis Anda menghasilkan pendapatan',
    },
    
    // PDF/CSV Labels
    pdfTitle: 'BUSINESS MODEL CANVAS',
    pdfSubtitle: 'Generated by AI Business Model Canvas Generator',
    pdfBusinessIdea: 'IDEA BISNIS:',
    csvSection: 'SECTION',
    csvItems: 'ITEMS',
  },
  en: {
    title: 'AI Business Model Canvas Generator',
    subtitle: 'Transform your business idea into a comprehensive Business Model Canvas with AI',
    describeIdea: 'Describe Your Business Idea',
    placeholder: 'Example: A marketplace platform connecting local farmers with consumers in major cities. Focus on fresh organic products with pre-order system and same-day delivery...',
    errorEmpty: 'Please enter a description of your business idea.',
    generate: 'Generate Business Model Canvas',
    generating: 'Generating Business Model Canvas...',
    download: 'Download',
    downloadTxt: 'Download TXT',
    downloadPdf: 'Download PDF',
    downloadCsv: 'Download CSV',
    newIdea: 'Create New',
    businessIdea: 'Your Business Idea:',
    businessModelCanvas: 'BUSINESS MODEL CANVAS',
    
    // BMC Blocks
    keyPartners: 'Key Partners',
    keyActivities: 'Key Activities',
    keyResources: 'Key Resources',
    valuePropositions: 'Value Propositions',
    customerRelationships: 'Customer Relationships',
    channels: 'Channels',
    customerSegments: 'Customer Segments',
    costStructure: 'Cost Structure',
    revenueStreams: 'Revenue Streams',
    
    // Tooltips
    tooltips: {
      keyPartners: 'Key partners who help your business operate and achieve its goals',
      keyActivities: 'Core activities required to run your business model',
      keyResources: 'Assets and resources needed to create value',
      valuePropositions: 'Unique value offered to customers',
      customerRelationships: 'How you interact and build relationships with customers',
      channels: 'Distribution channels to reach and serve customers',
      customerSegments: 'Target customer groups you want to serve',
      costStructure: 'Major costs involved in running the business',
      revenueStreams: 'How your business generates revenue',
    },
    
    // PDF/CSV Labels
    pdfTitle: 'BUSINESS MODEL CANVAS',
    pdfSubtitle: 'Generated by AI Business Model Canvas Generator',
    pdfBusinessIdea: 'BUSINESS IDEA:',
    csvSection: 'SECTION',
    csvItems: 'ITEMS',
  },
};

export const getTranslation = (lang, key) => {
  const keys = key.split('.');
  let value = translations[lang];
  
  for (const k of keys) {
    value = value?.[k];
  }
  
  return value || key;
};
