'use client';

import Image from 'next/image';
import { useRef, useState } from 'react';
import { Sparkles, Loader2, Download, RefreshCw, HelpCircle, Globe } from 'lucide-react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import Papa from 'papaparse';
import { translations, getTranslation } from '@/lib/translations';

const initialState = {
  keyPartners: [],
  keyActivities: [],
  keyResources: [],
  valuePropositions: [],
  customerRelationships: [],
  channels: [],
  customerSegments: [],
  costStructure: [],
  revenueStreams: [],
};



export default function Home() {
  const [businessIdea, setBusinessIdea] = useState('');
  const [loading, setLoading] = useState(false);
  const [bmcData, setBmcData] = useState(null);
  const [error, setError] = useState('');
  const [downloadFormat, setDownloadFormat] = useState('txt');
  const [showTooltip, setShowTooltip] = useState(null);
  const [language, setLanguage] = useState('id');
  const bmcContainerRef = useRef(null);

  const t = (key) => getTranslation(language, key);

  const generateBMC = async () => {
    if (!businessIdea.trim()) {
      setError(t('errorEmpty'));
      return;
    }

    setLoading(true);
    setError('');

    try {
      const response = await fetch('/api/bmc', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ idea: businessIdea, language }),
      });

      const result = await response.json().catch(() => null);

       if (!response.ok || !result) {
         throw new Error(result?.error || (language === 'id' ? 'Gagal menghasilkan Business Model Canvas.' : 'Failed to generate Business Model Canvas.'));
       }

      setBmcData({
        ...initialState,
        ...result.canvas,
      });
    } catch (err) {
      setError(err.message || (language === 'id' ? 'Terjadi kesalahan tak terduga.' : 'An unexpected error occurred.'));
    } finally {
      setLoading(false);
    }
  };

  const downloadBMC = (format = downloadFormat) => {
    if (!bmcData) return;

    if (format === 'txt') {
      downloadTXT();
    } else if (format === 'pdf') {
      downloadPDF();
    } else if (format === 'csv') {
      downloadCSV();
    }
  };

  const downloadTXT = () => {
    const labels = {
      id: {
        title: 'BUSINESS MODEL CANVAS',
        subtitle: 'Generated by AI Business Model Canvas Generator',
        businessIdea: 'IDEA BISNIS:',
        keyPartners: 'KEY PARTNERS (Mitra Kunci):',
        keyActivities: 'KEY ACTIVITIES (Aktivitas Kunci):',
        keyResources: 'KEY RESOURCES (Sumber Daya Kunci):',
        valuePropositions: 'VALUE PROPOSITIONS (Proposisi Nilai):',
        customerRelationships: 'CUSTOMER RELATIONSHIPS (Hubungan Pelanggan):',
        channels: 'CHANNELS (Saluran):',
        customerSegments: 'CUSTOMER SEGMENTS (Segmen Pelanggan):',
        costStructure: 'COST STRUCTURE (Struktur Biaya):',
        revenueStreams: 'REVENUE STREAMS (Aliran Pendapatan):',
      },
      en: {
        title: 'BUSINESS MODEL CANVAS',
        subtitle: 'Generated by AI Business Model Canvas Generator',
        businessIdea: 'BUSINESS IDEA:',
        keyPartners: 'KEY PARTNERS:',
        keyActivities: 'KEY ACTIVITIES:',
        keyResources: 'KEY RESOURCES:',
        valuePropositions: 'VALUE PROPOSITIONS:',
        customerRelationships: 'CUSTOMER RELATIONSHIPS:',
        channels: 'CHANNELS:',
        customerSegments: 'CUSTOMER SEGMENTS:',
        costStructure: 'COST STRUCTURE:',
        revenueStreams: 'REVENUE STREAMS:',
      },
    };

    const l = labels[language];
    const content = `${l.title}
${l.subtitle}

${l.businessIdea}
${businessIdea}

========================================

${l.keyPartners}
${bmcData.keyPartners.map((item, i) => `${i + 1}. ${item}`).join('\n')}

${l.keyActivities}
${bmcData.keyActivities.map((item, i) => `${i + 1}. ${item}`).join('\n')}

${l.keyResources}
${bmcData.keyResources.map((item, i) => `${i + 1}. ${item}`).join('\n')}

${l.valuePropositions}
${bmcData.valuePropositions.map((item, i) => `${i + 1}. ${item}`).join('\n')}

${l.customerRelationships}
${bmcData.customerRelationships.map((item, i) => `${i + 1}. ${item}`).join('\n')}

${l.channels}
${bmcData.channels.map((item, i) => `${i + 1}. ${item}`).join('\n')}

${l.customerSegments}
${bmcData.customerSegments.map((item, i) => `${i + 1}. ${item}`).join('\n')}

${l.costStructure}
${bmcData.costStructure.map((item, i) => `${i + 1}. ${item}`).join('\n')}

${l.revenueStreams}
${bmcData.revenueStreams.map((item, i) => `${i + 1}. ${item}`).join('\n')}`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'business-model-canvas.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const downloadPDF = async () => {
    if (!bmcContainerRef.current) return;

    const canvas = await html2canvas(bmcContainerRef.current, {
      scale: 2,
      backgroundColor: '#ffffff',
      useCORS: true,
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = pdf.internal.pageSize.getHeight();
    const imgWidth = pdfWidth;
    const imgHeight = (canvas.height * pdfWidth) / canvas.width;

    let heightLeft = imgHeight;
    let position = 0;

    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pdfHeight;

    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pdfHeight;
    }

    pdf.save('business-model-canvas.pdf');
  };

  const downloadCSV = () => {
    const labels = {
      id: {
        title: 'BUSINESS MODEL CANVAS',
        subtitle: 'Generated by AI Business Model Canvas Generator',
        businessIdea: 'IDEA BISNIS',
        section: 'SECTION',
        items: 'ITEMS',
        keyPartners: 'KEY PARTNERS',
        keyActivities: 'KEY ACTIVITIES',
        keyResources: 'KEY RESOURCES',
        valuePropositions: 'VALUE PROPOSITIONS',
        customerRelationships: 'CUSTOMER RELATIONSHIPS',
        channels: 'CHANNELS',
        customerSegments: 'CUSTOMER SEGMENTS',
        costStructure: 'COST STRUCTURE',
        revenueStreams: 'REVENUE STREAMS',
      },
      en: {
        title: 'BUSINESS MODEL CANVAS',
        subtitle: 'Generated by AI Business Model Canvas Generator',
        businessIdea: 'BUSINESS IDEA',
        section: 'SECTION',
        items: 'ITEMS',
        keyPartners: 'KEY PARTNERS',
        keyActivities: 'KEY ACTIVITIES',
        keyResources: 'KEY RESOURCES',
        valuePropositions: 'VALUE PROPOSITIONS',
        customerRelationships: 'CUSTOMER RELATIONSHIPS',
        channels: 'CHANNELS',
        customerSegments: 'CUSTOMER SEGMENTS',
        costStructure: 'COST STRUCTURE',
        revenueStreams: 'REVENUE STREAMS',
      },
    };

    const l = labels[language];
    const csvData = [
      [l.title],
      [l.subtitle],
      [],
      [l.businessIdea, businessIdea],
      [],
      [l.section, l.items],
      [l.keyPartners, bmcData.keyPartners.join('; ')],
      [l.keyActivities, bmcData.keyActivities.join('; ')],
      [l.keyResources, bmcData.keyResources.join('; ')],
      [l.valuePropositions, bmcData.valuePropositions.join('; ')],
      [l.customerRelationships, bmcData.customerRelationships.join('; ')],
      [l.channels, bmcData.channels.join('; ')],
      [l.customerSegments, bmcData.customerSegments.join('; ')],
      [l.costStructure, bmcData.costStructure.join('; ')],
      [l.revenueStreams, bmcData.revenueStreams.join('; ')],
    ];

    const csv = Papa.unparse(csvData);
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'business-model-canvas.csv';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const reset = () => {
    setBusinessIdea('');
    setBmcData(null);
    setError('');
  };

  const BMCBlock = ({ title, items = [], color, tooltipKey }) => {
    const isTooltipVisible = showTooltip === tooltipKey;
    const tooltipText = t(`tooltips.${tooltipKey}`);

    return (
      <div className={`${color} rounded-lg p-4 shadow-md border-2 border-rose-100 relative`}>
        <div className="flex items-center justify-between mb-3">
          <h3 className="font-bold text-sm text-[#5c0b0b] uppercase tracking-wide flex-1">{title}</h3>
          <div className="relative">
            <button
              onMouseEnter={() => setShowTooltip(tooltipKey)}
              onMouseLeave={() => setShowTooltip(null)}
              onClick={() => setShowTooltip(isTooltipVisible ? null : tooltipKey)}
              className="ml-2 text-[#7a1515] hover:text-[#5c0b0b] transition-colors"
              title={language === 'id' ? 'Informasi tentang blok ini' : 'Information about this block'}
            >
              <HelpCircle className="w-4 h-4" />
            </button>
            {isTooltipVisible && (
              <div className="absolute right-0 top-full mt-2 bg-[#5c0b0b] text-white text-xs rounded-lg p-2 w-48 z-50 shadow-lg">
                {tooltipText}
              </div>
            )}
          </div>
        </div>
        <ul className="space-y-2">
          {items.map((item, index) => (
            <li key={index} className="text-sm text-gray-700 flex items-start">
              <span className="text-[#8b1d1d] mr-2 font-bold">•</span>
              <span>{item}</span>
            </li>
          ))}
        </ul>
      </div>
    );
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#2b0000] via-[#4f0a0a] to-[#7a1515] p-4 sm:p-6 text-white">
      <div className="max-w-7xl mx-auto">
        {/* Language Selector */}
        <div className="flex justify-end mb-4">
          <div className="flex gap-2 bg-white/10 rounded-lg p-2 backdrop-blur-sm">
            <button
              onClick={() => setLanguage('id')}
              className={`flex items-center gap-1 px-3 py-1 rounded transition-all ${
                language === 'id'
                  ? 'bg-[#7a1515] text-white'
                  : 'text-white/70 hover:text-white'
              }`}
            >
              <Globe className="w-4 h-4" />
              ID
            </button>
            <button
              onClick={() => setLanguage('en')}
              className={`flex items-center gap-1 px-3 py-1 rounded transition-all ${
                language === 'en'
                  ? 'bg-[#7a1515] text-white'
                  : 'text-white/70 hover:text-white'
              }`}
            >
              <Globe className="w-4 h-4" />
              EN
            </button>
          </div>
        </div>

        <div className="text-center mb-8 flex flex-col items-center gap-4">
          <div className="w-full max-w-[600px] mx-auto">
            <Image
              src="/logo.jpg"
              alt={language === 'id' ? 'Logo aplikasi' : 'Application logo'}
              width={1200}
              height={400}
              className="w-full h-auto rounded-xl border-4 border-white/80 shadow-xl object-cover"
              priority
            />
          </div>
          <div className="flex items-center gap-3">
            <Sparkles className="w-10 h-10 text-[#ffd966]" />
            <h1 className="text-4xl font-bold text-white text-balance">
              {t('title')}
            </h1>
            <Sparkles className="w-10 h-10 text-[#ffd966] hidden sm:block" />
          </div>
          <p className="text-rose-100 text-balance">
            {t('subtitle')}
          </p>
        </div>

        {!bmcData && (
          <div className="max-w-3xl mx-auto bg-white/95 rounded-xl shadow-lg p-8 mb-8 border border-rose-100 text-gray-900">
            <label className="block text-lg font-semibold text-[#5c0b0b] mb-3">
              {t('describeIdea')}
            </label>
            <textarea
              value={businessIdea}
              onChange={(e) => setBusinessIdea(e.target.value)}
              placeholder={t('placeholder')}
              className="w-full h-48 p-4 border-2 border-rose-200 rounded-lg focus:border-[#7a1515] focus:outline-none resize-none text-gray-800 bg-white/80"
              disabled={loading}
            />

            {error && (
              <div className="mt-4 p-4 bg-rose-50 border-l-4 border-rose-500 text-rose-700">
                {error}
              </div>
            )}

            <button
              onClick={generateBMC}
              disabled={loading}
              className="mt-6 w-full bg-gradient-to-r from-[#7a1515] via-[#911c1c] to-[#b91c1c] text-white py-4 px-6 rounded-lg font-semibold text-lg hover:from-[#8c1919] hover:to-[#cc2b2b] transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2 shadow-lg"
            >
              {loading ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  {t('generating')}
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5" />
                  {t('generate')}
                </>
              )}
            </button>
          </div>
        )}

        {bmcData && (
          <div className="space-y-6">
            <div className="bg-white/95 rounded-xl shadow-lg p-6 border border-rose-100 text-gray-900">
              <h2 className="text-xl font-bold text-[#5c0b0b] mb-2">{t('businessIdea')}</h2>
              <p className="text-gray-700 italic">{businessIdea}</p>
            </div>

            {error && (
              <div className="p-4 bg-red-50 border-l-4 border-red-500 text-red-700">
                {error}
              </div>
            )}

            <div className="flex flex-col gap-4 sm:flex-row sm:justify-between sm:items-center">
              <div className="flex gap-2">
                <select
                  value={downloadFormat}
                  onChange={(e) => setDownloadFormat(e.target.value)}
                  className="px-4 py-2 border-2 border-rose-200 rounded-lg bg-white text-gray-800 font-semibold hover:border-[#7a1515] transition-all"
                >
                  <option value="txt">{t('downloadTxt')}</option>
                  <option value="pdf">{t('downloadPdf')}</option>
                  <option value="csv">{t('downloadCsv')}</option>
                </select>
                <button
                  onClick={() => downloadBMC(downloadFormat)}
                  className="bg-[#047857] text-white py-2 px-6 rounded-lg font-semibold hover:bg-[#059669] transition-all flex items-center gap-2 shadow-md justify-center"
                >
                  <Download className="w-5 h-5" />
                  {t('download')}
                </button>
              </div>
              <button
                onClick={reset}
                className="bg-[#374151] text-white py-2 px-6 rounded-lg font-semibold hover:bg-[#111827] transition-all flex items-center gap-2 shadow-md justify-center"
              >
                <RefreshCw className="w-5 h-5" />
                {t('newIdea')}
              </button>
            </div>

            <div
              ref={bmcContainerRef}
              className="bg-white/95 rounded-xl shadow-2xl p-6 sm:p-8 border border-rose-100 text-gray-900"
            >
              <h2 className="text-3xl font-bold text-center text-[#5c0b0b] mb-8">
                {t('businessModelCanvas')}
              </h2>

              <div className="grid grid-cols-1 lg:grid-cols-5 gap-4 mb-4">
                <BMCBlock
                  title={t('keyPartners')}
                  items={bmcData.keyPartners}
                  color="bg-rose-50"
                  tooltipKey="keyPartners"
                />
                <div className="space-y-4">
                  <BMCBlock
                    title={t('keyActivities')}
                    items={bmcData.keyActivities}
                    color="bg-rose-100"
                    tooltipKey="keyActivities"
                  />
                  <BMCBlock
                    title={t('keyResources')}
                    items={bmcData.keyResources}
                    color="bg-rose-200/60"
                    tooltipKey="keyResources"
                  />
                </div>
                <BMCBlock
                  title={t('valuePropositions')}
                  items={bmcData.valuePropositions}
                  color="bg-rose-50"
                  tooltipKey="valuePropositions"
                />
                <div className="space-y-4">
                  <BMCBlock
                    title={t('customerRelationships')}
                    items={bmcData.customerRelationships}
                    color="bg-rose-100"
                    tooltipKey="customerRelationships"
                  />
                  <BMCBlock
                    title={t('channels')}
                    items={bmcData.channels}
                    color="bg-rose-50"
                    tooltipKey="channels"
                  />
                </div>
                <BMCBlock
                  title={t('customerSegments')}
                  items={bmcData.customerSegments}
                  color="bg-rose-100"
                  tooltipKey="customerSegments"
                />
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                <BMCBlock
                  title={t('costStructure')}
                  items={bmcData.costStructure}
                  color="bg-rose-50"
                  tooltipKey="costStructure"
                />
                <BMCBlock
                  title={t('revenueStreams')}
                  items={bmcData.revenueStreams}
                  color="bg-rose-100"
                  tooltipKey="revenueStreams"
                />
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
