'use client';

import Image from 'next/image';
import { useState } from 'react';
import { Sparkles, Loader2, Download, RefreshCw } from 'lucide-react';

const initialState = {
  keyPartners: [],
  keyActivities: [],
  keyResources: [],
  valuePropositions: [],
  customerRelationships: [],
  channels: [],
  customerSegments: [],
  costStructure: [],
  revenueStreams: [],
};

export default function Home() {
  const [businessIdea, setBusinessIdea] = useState('');
  const [loading, setLoading] = useState(false);
  const [bmcData, setBmcData] = useState(null);
  const [error, setError] = useState('');

  const generateBMC = async () => {
    if (!businessIdea.trim()) {
      setError('Mohon masukkan deskripsi ide bisnis Anda.');
      return;
    }

    setLoading(true);
    setError('');

    try {
      const response = await fetch('/api/bmc', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ idea: businessIdea }),
      });

      const result = await response.json().catch(() => null);

      if (!response.ok || !result) {
        throw new Error(result?.error || 'Gagal menghasilkan Business Model Canvas.');
      }

      setBmcData({
        ...initialState,
        ...result.canvas,
      });
    } catch (err) {
      setError(err.message || 'Terjadi kesalahan tak terduga.');
    } finally {
      setLoading(false);
    }
  };

  const downloadBMC = () => {
    if (!bmcData) return;

    const content = `BUSINESS MODEL CANVAS
Generated by AI Business Model Canvas Generator

IDEA BISNIS:
${businessIdea}

========================================

KEY PARTNERS (Mitra Kunci):
${bmcData.keyPartners.map((item, i) => `${i + 1}. ${item}`).join('\n')}

KEY ACTIVITIES (Aktivitas Kunci):
${bmcData.keyActivities.map((item, i) => `${i + 1}. ${item}`).join('\n')}

KEY RESOURCES (Sumber Daya Kunci):
${bmcData.keyResources.map((item, i) => `${i + 1}. ${item}`).join('\n')}

VALUE PROPOSITIONS (Proposisi Nilai):
${bmcData.valuePropositions.map((item, i) => `${i + 1}. ${item}`).join('\n')}

CUSTOMER RELATIONSHIPS (Hubungan Pelanggan):
${bmcData.customerRelationships.map((item, i) => `${i + 1}. ${item}`).join('\n')}

CHANNELS (Saluran):
${bmcData.channels.map((item, i) => `${i + 1}. ${item}`).join('\n')}

CUSTOMER SEGMENTS (Segmen Pelanggan):
${bmcData.customerSegments.map((item, i) => `${i + 1}. ${item}`).join('\n')}

COST STRUCTURE (Struktur Biaya):
${bmcData.costStructure.map((item, i) => `${i + 1}. ${item}`).join('\n')}

REVENUE STREAMS (Aliran Pendapatan):
${bmcData.revenueStreams.map((item, i) => `${i + 1}. ${item}`).join('\n')}`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'business-model-canvas.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const reset = () => {
    setBusinessIdea('');
    setBmcData(null);
    setError('');
  };

  const BMCBlock = ({ title, items = [], color }) => (
    <div className={`${color} rounded-lg p-4 shadow-md border-2 border-rose-100`}>
      <h3 className="font-bold text-sm mb-3 text-[#5c0b0b] uppercase tracking-wide">{title}</h3>
      <ul className="space-y-2">
        {items.map((item, index) => (
          <li key={index} className="text-sm text-gray-700 flex items-start">
            <span className="text-[#8b1d1d] mr-2 font-bold">•</span>
            <span>{item}</span>
          </li>
        ))}
      </ul>
    </div>
  );

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#2b0000] via-[#4f0a0a] to-[#7a1515] p-4 sm:p-6 text-white">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-8 flex flex-col items-center gap-4">
          <div className="w-full max-w-[600px] mx-auto">
            <Image
              src="/logo.jpg"
              alt="Logo aplikasi"
              width={1200}
              height={400}
              className="w-full h-auto rounded-xl border-4 border-white/80 shadow-xl object-cover"
              priority
            />
          </div>
          <div className="flex items-center gap-3">
            <Sparkles className="w-10 h-10 text-[#ffd966]" />
            <h1 className="text-4xl font-bold text-white text-balance">
              AI Business Model Canvas Generator
            </h1>
            <Sparkles className="w-10 h-10 text-[#ffd966] hidden sm:block" />
          </div>
          <p className="text-rose-100 text-balance">
            Ubah ide bisnis Anda menjadi Business Model Canvas yang komprehensif dengan AI
          </p>
        </div>

        {!bmcData && (
          <div className="max-w-3xl mx-auto bg-white/95 rounded-xl shadow-lg p-8 mb-8 border border-rose-100 text-gray-900">
            <label className="block text-lg font-semibold text-[#5c0b0b] mb-3">
              Deskripsikan Ide Bisnis Anda
            </label>
            <textarea
              value={businessIdea}
              onChange={(e) => setBusinessIdea(e.target.value)}
              placeholder="Contoh: Platform marketplace yang menghubungkan petani lokal dengan konsumen di kota besar. Fokus pada produk organik segar dengan sistem pre-order dan pengiriman same-day..."
              className="w-full h-48 p-4 border-2 border-rose-200 rounded-lg focus:border-[#7a1515] focus:outline-none resize-none text-gray-800 bg-white/80"
              disabled={loading}
            />

            {error && (
              <div className="mt-4 p-4 bg-rose-50 border-l-4 border-rose-500 text-rose-700">
                {error}
              </div>
            )}

            <button
              onClick={generateBMC}
              disabled={loading}
              className="mt-6 w-full bg-gradient-to-r from-[#7a1515] via-[#911c1c] to-[#b91c1c] text-white py-4 px-6 rounded-lg font-semibold text-lg hover:from-[#8c1919] hover:to-[#cc2b2b] transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2 shadow-lg"
            >
              {loading ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  Menghasilkan Business Model Canvas...
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5" />
                  Generate Business Model Canvas
                </>
              )}
            </button>
          </div>
        )}

        {bmcData && (
          <div className="space-y-6">
            <div className="bg-white/95 rounded-xl shadow-lg p-6 border border-rose-100 text-gray-900">
              <h2 className="text-xl font-bold text-[#5c0b0b] mb-2">Ide Bisnis Anda:</h2>
              <p className="text-gray-700 italic">{businessIdea}</p>
            </div>

            {error && (
              <div className="p-4 bg-red-50 border-l-4 border-red-500 text-red-700">
                {error}
              </div>
            )}

            <div className="flex flex-col gap-4 sm:flex-row sm:justify-end">
              <button
                onClick={downloadBMC}
                className="bg-[#047857] text-white py-2 px-6 rounded-lg font-semibold hover:bg-[#059669] transition-all flex items-center gap-2 shadow-md justify-center"
              >
                <Download className="w-5 h-5" />
                Download BMC
              </button>
              <button
                onClick={reset}
                className="bg-[#374151] text-white py-2 px-6 rounded-lg font-semibold hover:bg-[#111827] transition-all flex items-center gap-2 shadow-md justify-center"
              >
                <RefreshCw className="w-5 h-5" />
                Buat Baru
              </button>
            </div>

            <div className="bg-white/95 rounded-xl shadow-2xl p-6 sm:p-8 border border-rose-100 text-gray-900">
              <h2 className="text-3xl font-bold text-center text-[#5c0b0b] mb-8">
                BUSINESS MODEL CANVAS
              </h2>

              <div className="grid grid-cols-1 lg:grid-cols-5 gap-4 mb-4">
                <BMCBlock
                  title="Key Partners"
                  items={bmcData.keyPartners}
                  color="bg-rose-50"
                />
                <div className="space-y-4">
                  <BMCBlock
                    title="Key Activities"
                    items={bmcData.keyActivities}
                    color="bg-rose-100"
                  />
                  <BMCBlock
                    title="Key Resources"
                    items={bmcData.keyResources}
                    color="bg-rose-200/60"
                  />
                </div>
                <BMCBlock
                  title="Value Propositions"
                  items={bmcData.valuePropositions}
                  color="bg-rose-50"
                />
                <div className="space-y-4">
                  <BMCBlock
                    title="Customer Relationships"
                    items={bmcData.customerRelationships}
                    color="bg-rose-100"
                  />
                  <BMCBlock title="Channels" items={bmcData.channels} color="bg-rose-50" />
                </div>
                <BMCBlock
                  title="Customer Segments"
                  items={bmcData.customerSegments}
                  color="bg-rose-100"
                />
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                <BMCBlock
                  title="Cost Structure"
                  items={bmcData.costStructure}
                  color="bg-rose-50"
                />
                <BMCBlock
                  title="Revenue Streams"
                  items={bmcData.revenueStreams}
                  color="bg-rose-100"
                />
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
